### ISSUE TITLE
TeSSLatraces

### ISSUE THREAD

**Issue by Surajj4837-th** [HendrikStreichhahn/MdF4TeSSLaConverter#1]
Your Readme.txt file says: **This program converts MDF4 files into TeSSLatraces.** 
I tried searching about **TeSSLatraces**, there are no relavant results. What kind of format is **TeSSLatraces**?

**Comment by HendrikStreichhahn** [comment]
TeSSLa stands for  **te**mporal **s**tream-based **s**pecification **la**nguage. One of TeSSLas main purpose is monitoring the time behavior of cyber-physical systems. You can learn more about it at [www.tessla.io](tessla.io).

TeSSLa traces are one way to get the streams into TeSSLa. The trace files are storing the events (or measurement values, etc.) combined with an associated timestamp. The trace file have a pretty simple and human readable format:

_timestamp_ : _stream name_ = _value_

591: stream1 = 5
602: stream1 = 9

See [https://github.com/HendrikStreichhahn/TeSSLa-Autosar-Timing-Extensions/tree/master/test/traces](url) for more example traces.

If you have any further questions, please do not hesitate to ask.

Best regards
Hendrik Streichhahn

**Comment by Surajj4837-th** [comment]
Thanks @HendrikStreichhahn for the explaination.

Also in the same readme file it is given that **MDF4Reader.dll** is required for the project. That means the project is built only for Windows platform. Are you planing to built the same for Ubuntu platform?

**Comment by HendrikStreichhahn** [comment]
The converter uses the free Turbolab DLL for reading the MDF4-Files and outputs the data in the TeSSLa trace format.

A Linux port of the converter would be possible, if there is a suitable replacement for the reading part of the DLL. But unfortunately, i didn't find one yet.
